title: Haroon Sajjad
email: haroon.sajjad@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Web Developer & Designer | WordPress, Laravel, Node, React
baseurl: "/resume" # the subpath of your site, e.g. /blog
url: "https://haroon-sajjad.github.io" # the base hostname & protocol for your site
github_username: haroon-sajjad

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
